[tool.poetry]
name = "tom-keck"
version = "0.1.0"
description = "TOMToolkit Facility module for W. M. Keck Observatory."
authors = ["Lindy Lindstrom <llindstrom@lco.global>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.0,<3.15"
tomtoolkit = "<4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
