# Generated by Django 5.2.16 on 2026-07-09 16:29

import django.db.models.deletion
import tom_common.encryption
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeckProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keck_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keck Username')),
                ('keck_password', tom_common.encryption.EncryptedModelField(blank=True, editable=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
