# Generated by Django 5.2.16 on 2026-07-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_keck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keckprofile',
            name='keck_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keck Username'),
        ),
    ]
